version: "3.9"

services:
  devopsdb:
    image: mydb
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123  

  application:
    image: myapp
    ports:
      - "1111:8080"
    depends_on:
      - devopsdb
    networks:
      - mynetwork
      
networks:
  mynetwork:
    driver: bridge
